"""init

Revision ID: 1e0832a3d375
Revises: 
Create Date: 2026-05-28 16:58:36.546049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0832a3d375'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('address', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'address')
    op.drop_column('employees', 'age')
    # ### end Alembic commands ###
