"""modified the schema for employee, added pass and role

Revision ID: 3491008bfd6e
Revises: 3e9528e2fc88
Create Date: 2026-05-29 16:05:06.793521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3491008bfd6e'
down_revision: Union[str, Sequence[str], None] = '3e9528e2fc88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.execute("UPDATE employees SET password_hash = 'placeholder' WHERE password_hash IS NULL")
    op.alter_column("employees","password_hash", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'password_hash')
    # ### end Alembic commands ###
