"""added unique constraint to emp table

Revision ID: 85e6a9a371c9
Revises: f68ebd16d56d
Create Date: 2026-06-02 21:47:33.132463

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "85e6a9a371c9"
down_revision: Union[str, Sequence[str], None] = "f68ebd16d56d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "employees", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "employees", type_="unique")
    # ### end Alembic commands ###
