"""created emp_dep_assoc table for association

Revision ID: aaeaaf96df87
Revises: 3491008bfd6e
Create Date: 2026-05-31 15:33:20.058809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aaeaaf96df87"
down_revision: Union[str, Sequence[str], None] = "3491008bfd6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emp_dep_assoc",
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"], ["department.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emp_dep_assoc_department_id"),
        "emp_dep_assoc",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emp_dep_assoc_employee_id"),
        "emp_dep_assoc",
        ["employee_id"],
        unique=False,
    )
    op.create_index(op.f("ix_emp_dep_assoc_id"), "emp_dep_assoc", ["id"], unique=False)
    op.drop_constraint(op.f("employees_email_key"), "employees", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("employees_email_key"),
        "employees",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_emp_dep_assoc_id"), table_name="emp_dep_assoc")
    op.drop_index(op.f("ix_emp_dep_assoc_employee_id"), table_name="emp_dep_assoc")
    op.drop_index(op.f("ix_emp_dep_assoc_department_id"), table_name="emp_dep_assoc")
    op.drop_table("emp_dep_assoc")
    # ### end Alembic commands ###
