"""modifed emp table

Revision ID: f68ebd16d56d
Revises: aaeaaf96df87
Create Date: 2026-06-01 14:12:57.533604

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f68ebd16d56d"
down_revision: Union[str, Sequence[str], None] = "aaeaaf96df87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ROLE_ENUM = sa.Enum("UI", "UX", "Developer", "HR", name="employeerole")


def upgrade() -> None:
    """Upgrade schema."""
    _ROLE_ENUM.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees",
        sa.Column("role", _ROLE_ENUM, server_default="Developer", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "role")
    # ### end Alembic commands ###
